# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

least_squares <- function(N, M) {
    .Call(`_GRlaw_least_squares`, N, M)
}

maximum_likelihood_estimation <- function(data) {
    .Call(`_GRlaw_maximum_likelihood_estimation`, data)
}

find_b_value <- function(N, M, method = "ls") {
    .Call(`_GRlaw_find_b_value`, N, M, method)
}

rcpp_hello_world <- function() {
    .Call(`_GRlaw_rcpp_hello_world`)
}

