# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the cumulative frequency of seismic events with given magnitudes
#'
#' @param magnitudes A numeric vector containing the earthquake magnitudes from a given catalog.
#' @return A list containing the (sorted) vector \eqn{M} of magnitudes and the vector \eqn{N(M)} 
#' corresponding to the number of earthquakes of magnitude greater than or equal to \eqn{M}.
#' 
#' @export
#' @examples
#' cumulative_frequency(c(1, 1, 5))
#' cumulative_frequency(c(6, 5, 4, 3, 2, 1, 1))
#'
#' 
cumulative_frequency <- function(magnitudes) {
    .Call(`_GRlaw_cumulative_frequency`, magnitudes)
}

#' Fit the frequency-magnitude plot using linear least squares
#'
#'
#' @param N A numeric vector containing the number of earthquakes of magnitude M or greater.
#' @param M A numeric vector containing the earthquake magnitudes from a given catalog.
#' @return A list containing the productivity parameter \eqn{a} and the \eqn{b}-value. 
#' @export
#' @examples
#' // Load earthquakes data from the Istituto Nazionale di Geofisica e Vulcanologia (12. 10. 2019, last 7 days)
#' catalog <- read.csv(file="./data/terremoti_ultimi_7_giorni.csv", header = TRUE, sep = ",")
#' magnitudes <- catalog$Magnitude
#' // Replace missing values
#' magnitudes[21] <- 6.0
#' magnitudes[22] <- 2.1
#' magnitudes[40] <- 3.4
#' freq <- cumulative_frequency(magnitudes)
#' least_squares(freq$count, freq$magnitude)
#'
#' 
least_squares <- function(N, M) {
    .Call(`_GRlaw_least_squares`, N, M)
}

#' Estimate the b-value with the maximum likelihood method 
#'
#'
#' @param magnitudes A numeric vector containing the earthquake magnitudes from a given catalog.
#' @return The \eqn{b}-value obtained estimated with the maximum likelihood method.
#' @export
#' @examples
#' // Load earthquakes data from the Istituto Nazionale di Geofisica e Vulcanologia (12. 10. 2019, last 7 days)
#' catalog <- read.csv(file="./data/terremoti_ultimi_7_giorni.csv", header = TRUE, sep = ",")
#' magnitudes <- catalog$Magnitude
#' // Replace missing values
#' magnitudes[21] <- 6.0
#' magnitudes[22] <- 2.1
#' magnitudes[40] <- 3.4
#' freq <- cumulative_frequency(magnitudes)
#' maximum_likelihood_estimation(freq$magnitude)
#'
#' 
maximum_likelihood_estimation <- function(magnitudes) {
    .Call(`_GRlaw_maximum_likelihood_estimation`, magnitudes)
}

#' Estimate the b-value of an earthquake catalog
#'
#'
#' @param N A numeric vector containing the number of earthquakes of magnitude M or greater.
#' @param M A numeric vector containing the earthquake magnitudes from a given catalog.
#' @param method A string indicating the method to be used for the calculation of the \eqn{b}-value.
#' It can either be \code{"ls"} for linear least squares or \code{"mle"} for the maximum likelihood method.
#' @return The \eqn{b}-value obtained by applying the indicated method
#' @export
#' @examples
#' //' // Load earthquakes data from the Istituto Nazionale di Geofisica e Vulcanologia (12. 10. 2019, last 7 days)
#' catalog <- read.csv(file="./data/terremoti_ultimi_7_giorni.csv", header = TRUE, sep = ",")
#' magnitudes <- catalog$Magnitude
#' // Replace missing values
#' magnitudes[21] <- 6.0
#' magnitudes[22] <- 2.1
#' magnitudes[40] <- 3.4
#' freq <- cumulative_frequency(magnitudes)
#' find_b_value(freq$count, freq$magnitude, "ls")
#'
#' 
find_b_value <- function(N, M, method = "ls") {
    .Call(`_GRlaw_find_b_value`, N, M, method)
}

